global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using FolderCleaner.Interfaces;
global using FolderCleaner.Models;
global using FolderCleaner.Repositories;
global using FolderCleaner;
